[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"]}


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2pro"

[dev-dependencies]
reqwest = "0.12.12"